### ISSUE TITLE
Flask 서버, SpringBoot, React 연동 바랍니다.

### ISSUE THREAD

**Issue by kyunggwan** [K-Digital-4Wheel/Source-Code#10]
## Description
Rest API 규격에 맞춰서 URL 호환가능하게 작성 바랍니다.

## Todo
- [ ] todo1: URL이 맞는가
- [ ] todo2: 모델 학습한 결과가 잘 출력이 되는가

## ETC
기타사항

**Comment by slows14tem** [comment]
f41661b7ead4fbc9a82b3be62fb27710ae4c17d0

**Comment by kyunggwan** [comment]
f41661b7ead4fbc9a82b3be62fb27710ae4c17d0
