### ISSUE TITLE
Flask 서버에서 카테고리 분류모델을 구현해주세요

### ISSUE THREAD

**Issue by kyunggwan** [K-Digital-4Wheel/Source-Code#4]
## Description
카테고리 분류모델을 파이선 Flask 모델로 구현 바랍니다.

## Todo
- [x] todo1 :  model.pickle파일 생성
- [ ] todo2 : 입력 값이 왔을 때 모델 학습한 출력 값이 json 형태로 나오는지

## ETC
기타사항

**Comment by min0312** [comment]
카테고리
9c4af5d8b10f17417c1232c27cf9b04a8ca8ca48

피클
0f9af63f5837eacd0f11cacf579770c480765480

플라스크
543be5c1303f961b731321531c802bcdf346c025
